default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit]
fail_fast: true

repos:
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.22.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: ['@arrai-innovations/commitlint-config']
    - repo: https://github.com/syntaqx/git-hooks
      rev: v0.0.18
      hooks:
          - id: circleci-config-validate
            files: ^.circleci/config.yml$
    - repo:
          https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.3
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix]
          # Run the formatter.
          - id: ruff-format
