[tool.flake8]
exclude = ".git,*venv*"
max-complexity = 10
max-line-length = 120
extend-ignore = [
    # (flake8) Black incompatibility - see https://github.com/PyCQA/pycodestyle/issues/373
    "E203",
]

[tool.black]
line-length = 120

[tool.coverage.run]
branch = true
include = [
    "argparse_color_formatter.py",
    "tests.py",
]

[tool.coverage.report]
exclude_lines = [
    "if __name__ == '__main__'",
    "if six.PY2:",
    "if PY2:",
    "raise NotImplementedError",
    "except ImportError",
]
