[tool.flake8]
exclude = ".git,*venv*"
max-complexity = 10
max-line-length = 120
extend-ignore = [
    # (flake8) Black incompatibility - see https://github.com/PyCQA/pycodestyle/issues/373
    "E203",
]

[tool.black]
line-length = 120
