version: 2.1
orbs:
    utils: arrai/utils@1.16.3
    flake8: arrai/flake8@20.0.2
    pypi: arrai/pypi@3.1.0
    github: arrai/github@3.0.0
executors:
    python39:
        docker:
            - image: cimg/python:3.9
    python310:
        docker:
            - image: cimg/python:3.10
    python311:
        docker:
            - image: cimg/python:3.11
    python312:
        docker:
            - image: cimg/python:3.12
    python313:
        docker:
            - image: cimg/python:3.13
jobs:
    build:
        executor: python312
        resource_class: small
        steps:
            - checkout
            - run:
                name: "Install requirements"
                command: |
                    pip install --user --upgrade -r requirements.txt -r dev_requirements.txt | cat; test ${PIPESTATUS[0]} -eq 0
            - when:
                condition: << pipeline.git.tag >>
                steps:
                    - run:
                        name: "Verify scm tag matches software version"
                        command: |
                            DIST_VERSION=$(python -c 'from argparse_color_formatter import __version__; print(__version__)')
                            if [ -z "${DIST_VERSION}" ] || [ "${DIST_VERSION}" != "${CIRCLE_TAG}" ]; then
                                echo "Git tag: ${CIRCLE_TAG} does not match the release version: ${DIST_VERSION}"
                                exit 1
                            fi
            - run:
                name: "Build Package"
                command: python -m build --wheel
            - save_cache:
                paths:
                    - ~/project/dist
                key: build-{{ arch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
    install:
        parameters:
            executor:
                description: "Execution environment for the install test job."
                type: executor
                default: python312
        executor: <<parameters.executor>>
        resource_class: small
        steps:
            - restore_cache:
                keys:
                    - build-{{ arch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
            - run:
                  name: "Install wheel"
                  command: pip install ~/project/dist/*.whl
            - run:
                  name: "Import library"
                  command: python -c 'from argparse_color_formatter import ColorHelpFormatter'
    tests:
        parameters:
            executor:
                description: "Execution environment for the test job."
                type: executor
                default: python312
            version:
                description: "Python version to test against."
                type: string
                default: "3.12"
        executor: <<parameters.executor>>
        resource_class: small
        circleci_ip_ranges: true
        steps:
            - checkout
            - utils/add_ssh_config
            - when:
                condition:
                    equal: [ main, << pipeline.git.branch >> ]
                steps:
                    - utils/make_status_shield:
                        status: running
                        color: lightblue
                    - utils/rsync_file:
                        file: ~/status.svg
                        remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.svg
                        host: docs
            - run:
                name: "Install test requirements"
                command: pip install -r requirements.txt -r dev_requirements.txt | cat; test ${PIPESTATUS[0]} -eq 0
            - run:
                name: "Run tests"
                command: coverage run -m unittest tests
            - run:
                when: always
                command: |
                    coverage html
                    coverage report | grep -oP '^TOTAL.*\d' | awk '{print $NF}' >> /tmp/.coveragep
            - utils/rsync_folder:
                when: always
                folder: ./htmlcov/
                remote_folder: ${CIRCLE_BRANCH}/htmlcov_${CIRCLE_JOB}
                host: docs
            - run:
                name: "Create freeze file"
                when: always
                command: pipenv run pip freeze > ~/pip.freeze
            - utils/rsync_file:
                when: always
                file: ~/pip.freeze
                remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.freeze
                host: docs
            - when:
                condition:
                    equal: [ main, << pipeline.git.branch >> ]
                steps:
                    - utils/make_coverage_shield:
                        when: always
                        link: "https://${DOCS_HOST}/${CIRCLE_PROJECT_REPONAME}/artifacts/${CIRCLE_BRANCH}/htmlcov_${CIRCLE_JOB}/"
                    - utils/rsync_file:
                        when: always
                        file: /tmp/coverage.svg
                        remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.coverage.svg
                        host: docs
                    - utils/make_status_shield:
                        when: on_success
                        status: passed
                        color: brightgreen
                    - utils/make_status_shield:
                        when: on_fail
                        status: failed
                        color: red
                    - utils/rsync_file:
                        when: always
                        file: ~/status.svg
                        remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.svg
                        host: docs
workflows:
    test_and_build:
        jobs:
            - tests:
                name: python39
                context: arrai-global
                executor: python39
                version: "3.9"
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                name: python310
                context: arrai-global
                executor: python310
                version: "3.10"
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                name: python311
                context: arrai-global
                executor: python311
                version: "3.11"
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - tests:
                  name: python312
                  context: arrai-global
                  executor: python312
                  version: "3.12"
                  filters:
                      branches:
                          only: /.*/
                      tags:
                          only: /.*/
            - tests:
                  name: python313
                  context: arrai-global
                  executor: python313
                  version: "3.13"
                  filters:
                      branches:
                          only: /.*/
                      tags:
                          only: /.*/
            - build:
                name: build
                requires:
                    - python39
                    - python310
                    - python311
                    - python312
                    - python313
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - install:
                name: python39_install
                executor: python39
                requires:
                    - build
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - install:
                name: python310_install
                executor: python310
                requires:
                    - build
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - install:
                name: python311_install
                executor: python311
                requires:
                    - build
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/
            - install:
                  name: python312_install
                  executor: python312
                  requires:
                      - build
                  filters:
                      branches:
                          only: /.*/
                      tags:
                          only: /.*/
            - install:
                  name: python313_install
                  executor: python313
                  requires:
                      - build
                  filters:
                      branches:
                          only: /.*/
                      tags:
                          only: /.*/
            - github/create_release:
                name: release_on_github
                context: arrai-global
                requires:
                    - python39_install
                    - python310_install
                    - python311_install
                    - python312_install
                    - python313_install
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
            - pypi/upload_release:
                name: publish
                context: arrai-public-package-publishing
                executor: python312
                cache_key: build-{{ arch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
                requires:
                    - python39_install
                    - python310_install
                    - python311_install
                    - python312_install
                    - python313_install
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
    lint:
        jobs:
            - flake8/flake8_pipenv_fixed_ip:
                name: flake8
                flake8_cmd: pflake8
                context: arrai-global
                executor: python311
                wd: ~/project
                filters:
                    branches:
                        only:
                            - main
            - flake8/flake8:
                name: flake8-no-badge
                flake8_cmd: pflake8
                executor: python311
                create_badges: false
                wd: ~/project
                filters:
                    branches:
                        ignore:
                            - main
